-------------------------------------------------------
-- create user, grant
CREATE USER TESTDB IDENTIFIED BY 1234;
GRANT DBA, RESOURCE, CONNECT TO TESTDB;

--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

CREATE TABLE "TESTDB"."ADMIN"
(	"ADMIN_ID" VARCHAR2(500 BYTE),
     "ADMIN_PW" VARCHAR2(500 BYTE)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FRIEND
--------------------------------------------------------

CREATE TABLE "TESTDB"."FRIEND"
(	"FRIEND_INDEX" NUMBER,
     "FRIEND_TOID" VARCHAR2(500 BYTE),
     "FRIEND_FROMID" VARCHAR2(500 BYTE),
     "FRIEND_REQDATE" TIMESTAMP (6),
     "FRIEND_STATUS" VARCHAR2(1 BYTE) DEFAULT 0
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HASHTAG
--------------------------------------------------------

CREATE TABLE "TESTDB"."HASHTAG"
(	"HASH_INDEX" NUMBER,
     "HASH_NAME" VARCHAR2(3000 BYTE)
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ILIKE
--------------------------------------------------------

CREATE TABLE "TESTDB"."ILIKE"
(	"POST_INDEX" NUMBER,
     "MEM_ID" VARCHAR2(500 BYTE),
     "ILIKE_DATE" TIMESTAMP (6)
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INQUIRY
--------------------------------------------------------

CREATE TABLE "TESTDB"."INQUIRY"
(	"INQUIRY_INDEX" NUMBER,
     "MEM_ID" VARCHAR2(500 BYTE),
     "INQUIRY_TITLE" VARCHAR2(500 BYTE),
     "INQUIRY_CON" VARCHAR2(3000 BYTE),
     "INQUIRY_DATE" TIMESTAMP (6),
     "INQUIRY_ISPUBLIC" VARCHAR2(1 BYTE) DEFAULT 1,
     "INQUIRY_COMMENT" VARCHAR2(3000 BYTE),
     "INQUIRY_COMMENT_DATE" DATE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOCATION
--------------------------------------------------------

CREATE TABLE "TESTDB"."LOCATION"
(	"LOCAL_NAME" VARCHAR2(30 BYTE),
     "LOCAL_NX" VARCHAR2(20 BYTE),
     "LOCAL_NY" VARCHAR2(20 BYTE)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

CREATE TABLE "TESTDB"."MEMBER"
(	"MEM_ID" VARCHAR2(500 BYTE),
     "MEM_PW" VARCHAR2(500 BYTE),
     "MEM_NICKNAME" VARCHAR2(500 BYTE),
     "MEM_NAME" VARCHAR2(500 BYTE),
     "MEM_ADDR" VARCHAR2(100 BYTE),
     "MEM_PHONE" VARCHAR2(20 BYTE),
     "MEM_BIR" DATE,
     "MEM_GEN" VARCHAR2(10 BYTE),
     "MEM_JOINDATE" TIMESTAMP (6),
     "MEM_LEAVEDATE" TIMESTAMP (6),
     "MEM_LEAVECODE" NUMBER,
     "MEM_LEAVEREASON" VARCHAR2(3000 BYTE)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOTICE
--------------------------------------------------------

CREATE TABLE "TESTDB"."NOTICE"
(	"NOTICE_INDEX" NUMBER,
     "NOTICE_TITLE" VARCHAR2(3000 BYTE),
     "NOTICE_CON" VARCHAR2(3000 BYTE),
     "NOTICE_DATE" TIMESTAMP (6)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOTIFICATION
--------------------------------------------------------

CREATE TABLE "TESTDB"."NOTIFICATION"
(	"NOTIFICATION_INDEX" NUMBER,
     "NOTIFICATION_TOID" VARCHAR2(500 BYTE),
     "NOTIFICATION_FROMID" VARCHAR2(500 BYTE),
     "NOTIFICATION_TARGET" NUMBER,
     "NOTIFICATION_TYPE" VARCHAR2(500 BYTE),
     "NOTIFICATION_CON" VARCHAR2(3000 BYTE),
     "NOTIFICATION_DATE" TIMESTAMP (6),
     "NOTIFICATION_ISREAD" VARCHAR2(1 BYTE) DEFAULT 0
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POST
--------------------------------------------------------

CREATE TABLE "TESTDB"."POST"
(	"POST_INDEX" NUMBER,
     "MEM_ID" VARCHAR2(500 BYTE),
     "POST_CON" VARCHAR2(3000 BYTE),
     "POST_PHOTO" VARCHAR2(3000 BYTE),
     "POST_DATE" TIMESTAMP (6),
     "POST_VISIBLE" VARCHAR2(20 BYTE),
     "POST_REPLYCNT" NUMBER,
     "POST_ILIKECNT" NUMBER,
     "POST_VIEWCNT" NUMBER
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POSTHASHTAG
--------------------------------------------------------

CREATE TABLE "TESTDB"."POSTHASHTAG"
(	"POST_INDEX" NUMBER,
     "HASH_INDEX" NUMBER
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROFILE
--------------------------------------------------------

CREATE TABLE "TESTDB"."PROFILE"
(	"MEM_ID" VARCHAR2(500 BYTE),
     "PROFILE_INTRO" VARCHAR2(3000 BYTE),
     "PROFILE_HEADERPHOTO" VARCHAR2(3000 BYTE),
     "PROFILE_PHOTO" VARCHAR2(3000 BYTE),
     "PROFILE_FRIENDCNT" NUMBER,
     "PROFILE_POSTCNT" NUMBER,
     "PROFILE_URL" VARCHAR2(3000 BYTE),
     "MEM_BIR" DATE
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REPLY
--------------------------------------------------------

CREATE TABLE "TESTDB"."REPLY"
(	"REPLY_INDEX" NUMBER,
     "POST_INDEX" NUMBER,
     "REPLY_PARENTREPLYINDEX" NUMBER,
     "MEM_ID" VARCHAR2(500 BYTE),
     "REPLY_DATE" TIMESTAMP (6),
     "REPLY_CON" VARCHAR2(3000 BYTE)
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REPORT
--------------------------------------------------------

CREATE TABLE "TESTDB"."REPORT"
(	"REPORT_INDEX" NUMBER,
     "REPORT_TOID" VARCHAR2(500 BYTE),
     "REPORT_FROMID" VARCHAR2(500 BYTE),
     "REPORT_CON" VARCHAR2(3000 BYTE),
     "REPORT_TYPE" VARCHAR2(500 BYTE),
     "REPORT_PATH" VARCHAR2(3000 BYTE),
     "REPORT_DATE" TIMESTAMP (6),
     "REPORT_STATUS" VARCHAR2(1 BYTE),
     "REPORT_PRODATE" TIMESTAMP (6),
     "REPORT_PHOTO" VARCHAR2(3000 BYTE)
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERSETTINGS
--------------------------------------------------------

CREATE TABLE "TESTDB"."USERSETTINGS"
(	"MEM_ID" VARCHAR2(500 BYTE),
     "SET_FRIEND" VARCHAR2(1 BYTE),
     "SET_ILIKE" VARCHAR2(1 BYTE),
     "SET_REPLY" VARCHAR2(1 BYTE),
     "SET_CHAT" VARCHAR2(1 BYTE),
     "SET_BIR" VARCHAR2(1 BYTE)
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


CREATE TABLE "TESTDB"."POST_PHOTO_DETAIL"
(   "POST_PHOTO" NUMBER,
    "POST_PHOTO_SN" NUMBER(5,0),
    "PHOTO_STRE_COURS" VARCHAR2(3000 BYTE),
    "PHOTO_FILE_NM" VARCHAR2(3000 BYTE),
    "ORG_PHOTO_NM" VARCHAR2(3000 BYTE),
    "PHOTO_EXTSN" VARCHAR2(500 BYTE)
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POST_PHOTO_TB
--------------------------------------------------------

CREATE TABLE "TESTDB"."POST_PHOTO_TB"
(   "POST_PHOTO" NUMBER
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_POST_PHOTO_DETAIL
--------------------------------------------------------

CREATE UNIQUE INDEX "TESTDB"."PK_POST_PHOTO_DETAIL" ON "TESTDB"."POST_PHOTO_DETAIL" ("POST_PHOTO")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_POST_PHOTO_TB
--------------------------------------------------------

CREATE UNIQUE INDEX "TESTDB"."PK_POST_PHOTO_TB" ON "TESTDB"."POST_PHOTO_TB" ("POST_PHOTO")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table POST_PHOTO_DETAIL
--------------------------------------------------------

ALTER TABLE "TESTDB"."POST_PHOTO_DETAIL" MODIFY ("POST_PHOTO" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."POST_PHOTO_DETAIL" ADD CONSTRAINT "PK_POST_PHOTO_DETAIL" PRIMARY KEY ("POST_PHOTO")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POST_PHOTO_TB
--------------------------------------------------------

ALTER TABLE "TESTDB"."POST_PHOTO_TB" MODIFY ("POST_PHOTO" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."POST_PHOTO_TB" ADD CONSTRAINT "PK_POST_PHOTO_TB" PRIMARY KEY ("POST_PHOTO")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POST_PHOTO_DETAIL
--------------------------------------------------------

ALTER TABLE "TESTDB"."POST_PHOTO_DETAIL" ADD CONSTRAINT "FK_POST_PHOTO_TB_TO_POST_PHOTO_DETAIL_1" FOREIGN KEY ("POST_PHOTO")
    REFERENCES "TESTDB"."POST_PHOTO_TB" ("POST_PHOTO") ON DELETE CASCADE ENABLE;


--------------------------------------------------------
--  DDL for Index PK_ADMIN
--------------------------------------------------------

CREATE UNIQUE INDEX "TESTDB"."PK_ADMIN" ON "TESTDB"."ADMIN" ("ADMIN_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_FRIEND
--------------------------------------------------------

CREATE UNIQUE INDEX "TESTDB"."PK_FRIEND" ON "TESTDB"."FRIEND" ("FRIEND_INDEX")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_HASHTAG
--------------------------------------------------------

CREATE UNIQUE INDEX "TESTDB"."PK_HASHTAG" ON "TESTDB"."HASHTAG" ("HASH_INDEX")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ILIKE
--------------------------------------------------------

CREATE UNIQUE INDEX "TESTDB"."PK_ILIKE" ON "TESTDB"."ILIKE" ("POST_INDEX", "MEM_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_INQUIRY
--------------------------------------------------------

CREATE UNIQUE INDEX "TESTDB"."PK_INQUIRY" ON "TESTDB"."INQUIRY" ("INQUIRY_INDEX")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MEMBER
--------------------------------------------------------

CREATE UNIQUE INDEX "TESTDB"."PK_MEMBER" ON "TESTDB"."MEMBER" ("MEM_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_NOTICE
--------------------------------------------------------

CREATE UNIQUE INDEX "TESTDB"."PK_NOTICE" ON "TESTDB"."NOTICE" ("NOTICE_INDEX")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_NOTIFICATION
--------------------------------------------------------

CREATE UNIQUE INDEX "TESTDB"."PK_NOTIFICATION" ON "TESTDB"."NOTIFICATION" ("NOTIFICATION_INDEX")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_POST
--------------------------------------------------------

CREATE UNIQUE INDEX "TESTDB"."PK_POST" ON "TESTDB"."POST" ("POST_INDEX")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_POSTHASHTAG
--------------------------------------------------------

CREATE UNIQUE INDEX "TESTDB"."PK_POSTHASHTAG" ON "TESTDB"."POSTHASHTAG" ("POST_INDEX", "HASH_INDEX")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PROFILE
--------------------------------------------------------

CREATE UNIQUE INDEX "TESTDB"."PK_PROFILE" ON "TESTDB"."PROFILE" ("MEM_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_REPLY
--------------------------------------------------------

CREATE UNIQUE INDEX "TESTDB"."PK_REPLY" ON "TESTDB"."REPLY" ("REPLY_INDEX")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_REPORT
--------------------------------------------------------

CREATE UNIQUE INDEX "TESTDB"."PK_REPORT" ON "TESTDB"."REPORT" ("REPORT_INDEX")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USERSETTINGS
--------------------------------------------------------

CREATE UNIQUE INDEX "TESTDB"."PK_USERSETTINGS" ON "TESTDB"."USERSETTINGS" ("MEM_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

ALTER TABLE "TESTDB"."ADMIN" MODIFY ("ADMIN_ID" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."ADMIN" ADD CONSTRAINT "PK_ADMIN" PRIMARY KEY ("ADMIN_ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
ALTER TABLE "TESTDB"."ADMIN" MODIFY ("ADMIN_PW" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FRIEND
--------------------------------------------------------

ALTER TABLE "TESTDB"."FRIEND" MODIFY ("FRIEND_INDEX" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."FRIEND" MODIFY ("FRIEND_TOID" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."FRIEND" MODIFY ("FRIEND_FROMID" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."FRIEND" ADD CONSTRAINT "PK_FRIEND" PRIMARY KEY ("FRIEND_INDEX")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HASHTAG
--------------------------------------------------------

ALTER TABLE "TESTDB"."HASHTAG" MODIFY ("HASH_INDEX" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."HASHTAG" ADD CONSTRAINT "PK_HASHTAG" PRIMARY KEY ("HASH_INDEX")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
ALTER TABLE "TESTDB"."HASHTAG" MODIFY ("HASH_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ILIKE
--------------------------------------------------------

ALTER TABLE "TESTDB"."ILIKE" MODIFY ("POST_INDEX" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."ILIKE" MODIFY ("MEM_ID" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."ILIKE" ADD CONSTRAINT "PK_ILIKE" PRIMARY KEY ("POST_INDEX", "MEM_ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INQUIRY
--------------------------------------------------------

ALTER TABLE "TESTDB"."INQUIRY" MODIFY ("INQUIRY_INDEX" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."INQUIRY" MODIFY ("MEM_ID" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."INQUIRY" ADD CONSTRAINT "PK_INQUIRY" PRIMARY KEY ("INQUIRY_INDEX")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
ALTER TABLE "TESTDB"."INQUIRY" MODIFY ("INQUIRY_TITLE" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."INQUIRY" MODIFY ("INQUIRY_CON" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

ALTER TABLE "TESTDB"."MEMBER" MODIFY ("MEM_PW" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."MEMBER" MODIFY ("MEM_ID" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY ("MEM_ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
ALTER TABLE "TESTDB"."MEMBER" MODIFY ("MEM_NICKNAME" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."MEMBER" MODIFY ("MEM_NAME" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."MEMBER" MODIFY ("MEM_ADDR" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."MEMBER" MODIFY ("MEM_PHONE" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."MEMBER" MODIFY ("MEM_BIR" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."MEMBER" MODIFY ("MEM_GEN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTICE
--------------------------------------------------------

ALTER TABLE "TESTDB"."NOTICE" MODIFY ("NOTICE_INDEX" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY ("NOTICE_INDEX")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
ALTER TABLE "TESTDB"."NOTICE" MODIFY ("NOTICE_TITLE" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."NOTICE" MODIFY ("NOTICE_CON" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTIFICATION
--------------------------------------------------------

ALTER TABLE "TESTDB"."NOTIFICATION" MODIFY ("NOTIFICATION_INDEX" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."NOTIFICATION" MODIFY ("NOTIFICATION_TOID" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."NOTIFICATION" ADD CONSTRAINT "PK_NOTIFICATION" PRIMARY KEY ("NOTIFICATION_INDEX")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POST
--------------------------------------------------------

ALTER TABLE "TESTDB"."POST" MODIFY ("POST_INDEX" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."POST" MODIFY ("MEM_ID" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."POST" ADD CONSTRAINT "PK_POST" PRIMARY KEY ("POST_INDEX")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POSTHASHTAG
--------------------------------------------------------

ALTER TABLE "TESTDB"."POSTHASHTAG" MODIFY ("POST_INDEX" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."POSTHASHTAG" MODIFY ("HASH_INDEX" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."POSTHASHTAG" ADD CONSTRAINT "PK_POSTHASHTAG" PRIMARY KEY ("POST_INDEX", "HASH_INDEX")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROFILE
--------------------------------------------------------

ALTER TABLE "TESTDB"."PROFILE" MODIFY ("MEM_ID" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."PROFILE" ADD CONSTRAINT "PK_PROFILE" PRIMARY KEY ("MEM_ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REPLY
--------------------------------------------------------

ALTER TABLE "TESTDB"."REPLY" MODIFY ("REPLY_INDEX" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."REPLY" MODIFY ("POST_INDEX" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."REPLY" MODIFY ("REPLY_PARENTREPLYINDEX" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."REPLY" MODIFY ("MEM_ID" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY ("REPLY_INDEX")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REPORT
--------------------------------------------------------

ALTER TABLE "TESTDB"."REPORT" MODIFY ("REPORT_INDEX" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."REPORT" MODIFY ("REPORT_TOID" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."REPORT" MODIFY ("REPORT_FROMID" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY ("REPORT_INDEX")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERSETTINGS
--------------------------------------------------------

ALTER TABLE "TESTDB"."USERSETTINGS" MODIFY ("MEM_ID" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."USERSETTINGS" ADD CONSTRAINT "PK_USERSETTINGS" PRIMARY KEY ("MEM_ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
ALTER TABLE "TESTDB"."USERSETTINGS" MODIFY ("SET_FRIEND" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."USERSETTINGS" MODIFY ("SET_ILIKE" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."USERSETTINGS" MODIFY ("SET_REPLY" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."USERSETTINGS" MODIFY ("SET_CHAT" NOT NULL ENABLE);
ALTER TABLE "TESTDB"."USERSETTINGS" MODIFY ("SET_BIR" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FRIEND
--------------------------------------------------------

ALTER TABLE "TESTDB"."FRIEND" ADD CONSTRAINT "FK_MEMBER_TO_FRIEND_1" FOREIGN KEY ("FRIEND_TOID")
    REFERENCES "TESTDB"."MEMBER" ("MEM_ID") ON DELETE CASCADE ENABLE;
ALTER TABLE "TESTDB"."FRIEND" ADD CONSTRAINT "FK_MEMBER_TO_FRIEND_2" FOREIGN KEY ("FRIEND_FROMID")
    REFERENCES "TESTDB"."MEMBER" ("MEM_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ILIKE
--------------------------------------------------------

ALTER TABLE "TESTDB"."ILIKE" ADD CONSTRAINT "FK_MEMBER_TO_ILIKE_1" FOREIGN KEY ("MEM_ID")
    REFERENCES "TESTDB"."MEMBER" ("MEM_ID") ON DELETE CASCADE ENABLE;
ALTER TABLE "TESTDB"."ILIKE" ADD CONSTRAINT "FK_POST_TO_ILIKE_1" FOREIGN KEY ("POST_INDEX")
    REFERENCES "TESTDB"."POST" ("POST_INDEX") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INQUIRY
--------------------------------------------------------

ALTER TABLE "TESTDB"."INQUIRY" ADD CONSTRAINT "FK_MEMBER_TO_INQUIRY_1" FOREIGN KEY ("MEM_ID")
    REFERENCES "TESTDB"."MEMBER" ("MEM_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTIFICATION
--------------------------------------------------------

ALTER TABLE "TESTDB"."NOTIFICATION" ADD CONSTRAINT "FK_MEMBER_TO_NOTIFICATION_1" FOREIGN KEY ("NOTIFICATION_TOID")
    REFERENCES "TESTDB"."MEMBER" ("MEM_ID") ON DELETE CASCADE ENABLE;
ALTER TABLE "TESTDB"."NOTIFICATION" ADD CONSTRAINT "FK_MEMBER_TO_NOTIFICATION_2" FOREIGN KEY ("NOTIFICATION_FROMID")
    REFERENCES "TESTDB"."MEMBER" ("MEM_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POST
--------------------------------------------------------

ALTER TABLE "TESTDB"."POST" ADD CONSTRAINT "FK_MEMBER_TO_POST_1" FOREIGN KEY ("MEM_ID")
    REFERENCES "TESTDB"."MEMBER" ("MEM_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POSTHASHTAG
--------------------------------------------------------

ALTER TABLE "TESTDB"."POSTHASHTAG" ADD CONSTRAINT "FK_HASHTAG_TO_POSTHASHTAG_1" FOREIGN KEY ("HASH_INDEX")
    REFERENCES "TESTDB"."HASHTAG" ("HASH_INDEX") ON DELETE CASCADE ENABLE;
ALTER TABLE "TESTDB"."POSTHASHTAG" ADD CONSTRAINT "FK_POST_TO_POSTHASHTAG_1" FOREIGN KEY ("POST_INDEX")
    REFERENCES "TESTDB"."POST" ("POST_INDEX") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROFILE
--------------------------------------------------------

ALTER TABLE "TESTDB"."PROFILE" ADD CONSTRAINT "FK_MEMBER_TO_PROFILE_1" FOREIGN KEY ("MEM_ID")
    REFERENCES "TESTDB"."MEMBER" ("MEM_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPLY
--------------------------------------------------------

ALTER TABLE "TESTDB"."REPLY" ADD CONSTRAINT "FK_MEMBER_TO_REPLY_1" FOREIGN KEY ("MEM_ID")
    REFERENCES "TESTDB"."MEMBER" ("MEM_ID") ON DELETE CASCADE ENABLE;
ALTER TABLE "TESTDB"."REPLY" ADD CONSTRAINT "FK_REPLY_TO_REPLY_1" FOREIGN KEY ("REPLY_PARENTREPLYINDEX")
    REFERENCES "TESTDB"."REPLY" ("REPLY_INDEX") ON DELETE CASCADE ENABLE;
ALTER TABLE "TESTDB"."REPLY" ADD CONSTRAINT "FK_POST_TO_REPLY_1" FOREIGN KEY ("POST_INDEX")
    REFERENCES "TESTDB"."POST" ("POST_INDEX") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPORT
--------------------------------------------------------

ALTER TABLE "TESTDB"."REPORT" ADD CONSTRAINT "FK_MEMBER_TO_REPORT_1" FOREIGN KEY ("REPORT_TOID")
    REFERENCES "TESTDB"."MEMBER" ("MEM_ID") ON DELETE CASCADE ENABLE;
ALTER TABLE "TESTDB"."REPORT" ADD CONSTRAINT "FK_MEMBER_TO_REPORT_2" FOREIGN KEY ("REPORT_FROMID")
    REFERENCES "TESTDB"."MEMBER" ("MEM_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERSETTINGS
--------------------------------------------------------

ALTER TABLE "TESTDB"."USERSETTINGS" ADD CONSTRAINT "FK_MEMBER_TO_USERSETTINGS_1" FOREIGN KEY ("MEM_ID")
    REFERENCES "TESTDB"."MEMBER" ("MEM_ID") ON DELETE CASCADE ENABLE;


-- 시퀀스
CREATE SEQUENCE  "TESTDB"."NUM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 24 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- welcome page location date
Insert into TESTDB.LOCATION (LOCAL_NAME,LOCAL_NX,LOCAL_NY) values ('서울특별시','60','127');
Insert into TESTDB.LOCATION (LOCAL_NAME,LOCAL_NX,LOCAL_NY) values ('부산광역시','98','76');
Insert into TESTDB.LOCATION (LOCAL_NAME,LOCAL_NX,LOCAL_NY) values ('대구광역시','89','90');
Insert into TESTDB.LOCATION (LOCAL_NAME,LOCAL_NX,LOCAL_NY) values ('인천광역시','55','124');
Insert into TESTDB.LOCATION (LOCAL_NAME,LOCAL_NX,LOCAL_NY) values ('광주광역시','58','74');
Insert into TESTDB.LOCATION (LOCAL_NAME,LOCAL_NX,LOCAL_NY) values ('대전광역시','67','100');
Insert into TESTDB.LOCATION (LOCAL_NAME,LOCAL_NX,LOCAL_NY) values ('울산광역시','102','84');
Insert into TESTDB.LOCATION (LOCAL_NAME,LOCAL_NX,LOCAL_NY) values ('세종특별자치시','66','103');
Insert into TESTDB.LOCATION (LOCAL_NAME,LOCAL_NX,LOCAL_NY) values ('경기도','60','120');
Insert into TESTDB.LOCATION (LOCAL_NAME,LOCAL_NX,LOCAL_NY) values ('충청북도','69','107');
Insert into TESTDB.LOCATION (LOCAL_NAME,LOCAL_NX,LOCAL_NY) values ('충청남도','68','100');
Insert into TESTDB.LOCATION (LOCAL_NAME,LOCAL_NX,LOCAL_NY) values ('전라남도','51','67');
Insert into TESTDB.LOCATION (LOCAL_NAME,LOCAL_NX,LOCAL_NY) values ('경상북도','87','106');
Insert into TESTDB.LOCATION (LOCAL_NAME,LOCAL_NX,LOCAL_NY) values ('경상남도','91','77');
Insert into TESTDB.LOCATION (LOCAL_NAME,LOCAL_NX,LOCAL_NY) values ('제주특별자치도','52','38');
Insert into TESTDB.LOCATION (LOCAL_NAME,LOCAL_NX,LOCAL_NY) values ('강원특별자치도','73','134');
Insert into TESTDB.LOCATION (LOCAL_NAME,LOCAL_NX,LOCAL_NY) values ('전북특별자치도','63','89');

-----------------------------------------------------------------------------------------------------------------------------
-- admin account
INSERT INTO ADMIN VALUES ('admin','123');

------------------------------------------------------------------------------------------------------------------------------

-- TEST DATA AREA
-- MEMBER + USERSETTINGS + PROFILE
INSERT INTO MEMBER VALUES ('jewoo827@naver.com','123','jewoo827','우정은','대전광역시','01096780827','1996/08/27','F', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('jewoo827@naver.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('jewoo827@naver.com', null, null, null, 0, 0, null, '1996/08/27');
INSERT INTO MEMBER VALUES ('test1@gmail.com','123','test1','곽용팔','서울특별시','01012345678','1984/04/30','M', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('test1@gmail.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('test1@gmail.com', null, null, null, 0, 0, null, '1984/04/30');
INSERT INTO MEMBER VALUES ('test4@gmail.com','123','test4','이순금','대구광역시','01011112222','1955/07/20','F', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('test4@gmail.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('test4@gmail.com', null, null, null, 0, 0, null, '1955/07/20');
INSERT INTO MEMBER VALUES ('semo@naver.com','123','semo','김세모','전북특별자치도','01055882213','1999/12/30','M', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('semo@naver.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('semo@naver.com', null, null, null, 0, 0, null, '1999/12/30');
INSERT INTO MEMBER VALUES ('nemo@daum.net','123','nemo','이네모','충청남도','01025789999','1987/01/01','F', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('nemo@daum.net', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('nemo@daum.net', null, null, null, 0, 0, null, '1987/01/01');
INSERT INTO MEMBER VALUES ('kbj@naver.com','123','kbj','김복자','인천광역시','01034567894','1960/02/15','F', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('kbj@naver.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('kbj@naver.com', null, null, null, 0, 0, null, '1960/02/15');
INSERT INTO MEMBER VALUES ('skfktkfkd@naver.com','123','skfktkfkd','이순신','세종특별자치시','01034567895','1944/01/03','M', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('skfktkfkd@naver.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('skfktkfkd@naver.com', null, null, null, 0, 0, null, '1944/01/03');
INSERT INTO MEMBER VALUES ('dlfwlao@naver.com','123','dlfwlao','일지매','경기도','01034567896','1943/12/12','F', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('dlfwlao@naver.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('dlfwlao@naver.com', null, null, null, 0, 0, null, '1943/12/12');
INSERT INTO MEMBER VALUES ('hong1@naver.com','123','hong1','홍길동','강원특별자치도','01034567897','1955/05/05','M', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('hong1@naver.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('hong1@naver.com', null, null, null, 0, 0, null, '1955/05/05');
INSERT INTO MEMBER VALUES ('hong2@naver.com','123','hong2','홍길순','제주특별자치도','01034567898','1977/05/13','F', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('hong2@naver.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('hong2@naver.com', null, null, null, 0, 0, null, '1977/05/13');
INSERT INTO MEMBER VALUES ('jdh00113@naver.com','123','jdh00113','전동현','경상남도','01034567899','2006/01/13','F', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('jdh00113@naver.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('jdh00113@naver.com', null, null, null, 0, 0, null, '2006/01/13');
INSERT INTO MEMBER VALUES ('bds0707@naver.com','123','bds0707','백두산','경상북도','01034567900','2012/07/07','M', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('bds0707@naver.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('bds0707@naver.com', null, null, null, 0, 0, null, '2012/07/07');
INSERT INTO MEMBER VALUES ('lovelove@naver.com','123','lovelove','유사랑','전라남도','01034567901','2012/07/08','F', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('lovelove@naver.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('lovelove@naver.com', null, null, null, 0, 0, null, '2012/07/08');
INSERT INTO MEMBER VALUES ('enji@naver.com','123','enji','서은지','충청북도','01034567902','2012/07/09','M', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('enji@naver.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('enji@naver.com', null, null, null, 0, 0, null, '2012/07/09');
INSERT INTO MEMBER VALUES ('bww123@naver.com','123','bww123','배우용','경기도','01034567903','2012/07/10','F', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('bww123@naver.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('bww123@naver.com', null, null, null, 0, 0, null, '2012/07/10');
INSERT INTO MEMBER VALUES ('qwe88@naver.com','123','qwe88','김철수','울산광역시','01034567904','2012/07/11','F', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('qwe88@naver.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('qwe88@naver.com', null, null, null, 0, 0, null, '2012/07/11');
INSERT INTO MEMBER VALUES ('asd66@naver.com','123','asd66','김영희','광주광역시','01034567905','2012/07/12','M', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('asd66@naver.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('asd66@naver.com', null, null, null, 0, 0, null, '2012/07/12');
INSERT INTO MEMBER VALUES ('kim222@naver.com','123','kim222','김두식','인천광역시','01034567906','2012/07/13','F', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('kim222@naver.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('kim222@naver.com', null, null, null, 0, 0, null, '2012/07/13');
INSERT INTO MEMBER VALUES ('kingkong@naver.com','123','kingkong','황보석','강원특별자치도','01034567907','2012/07/14','M', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('kingkong@naver.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('kingkong@naver.com', null, null, null, 0, 0, null, '2012/07/14');
INSERT INTO MEMBER VALUES ('dragonkim@naver.com','123','dragonkim','김용','제주특별자치도','01034567908','2012/07/15','F', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('dragonkim@naver.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('dragonkim@naver.com', null, null, null, 0, 0, null, '2012/07/15');
INSERT INTO MEMBER VALUES ('sjy0009@naver.com','123','sjy0009','서지연','경상남도','01034567909','2012/07/16','F', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('sjy0009@naver.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('sjy0009@naver.com', null, null, null, 0, 0, null, '2012/07/16');
INSERT INTO MEMBER VALUES ('sjh0009@naver.com','123','sjh0009','서지현','경상북도','01054878888','2012/07/17','M', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('sjh0009@naver.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('sjh0009@naver.com', null, null, null, 0, 0, null, '2012/07/17');
INSERT INTO MEMBER VALUES ('kangsj@naver.com','123','kangsj','강수진','전라남도','01015156464','2012/07/18','M', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('kangsj@naver.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('kangsj@naver.com', null, null, null, 0, 0, null, '2012/07/18');
INSERT INTO MEMBER VALUES ('ccc0719@naver.com','123','ccc0719','강수정','충청북도','01033448783','2012/07/19','M', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('ccc0719@naver.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('ccc0719@naver.com', null, null, null, 0, 0, null, '2012/07/19');
INSERT INTO MEMBER VALUES ('dditlove@naver.com','123','dditlove','이정현','경기도','01057894876','2012/07/20','M', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('dditlove@naver.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('dditlove@naver.com', null, null, null, 0, 0, null, '2012/07/20');
INSERT INTO MEMBER VALUES ('one111@naver.com','123','one111','이하나','충청북도','01034876655','2012/07/21','F', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('one111@naver.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('one111@naver.com', null, null, null, 0, 0, null, '2012/07/21');
INSERT INTO MEMBER VALUES ('you222@naver.com','123','you222','유연','경기도','01099998874','2012/07/22','M', SYSDATE, null, null, null);INSERT INTO USERSETTINGS VALUES ('you222@naver.com', 1, 1, 1, 1, 1); INSERT INTO PROFILE VALUES ('you222@naver.com', null, null, null, 0, 0, null, '2012/07/22');

--INQUIRY (문의) : 페이징 확인 위해 많이
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '0', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '0', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '0', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '0', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '0', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '0', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '0', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '0', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '0', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','페이징 확인용 더미','페이징 확인용 더미 문의 내용', SYSDATE, '1', null, null);"
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'jewoo827@naver.com','비밀번호 수정이 안됩니다.','비밀번호를 수정하는데 자꾸 오류가 발생하고 적용이 안됩니다. 확인 바랍니다.', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'test1@gmail.com','프로필 조회 시 오류 발생','안녕하세요. 다름이 아니라 프로필 조회 중에 오류를 발견하여 문의드립니다.', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'jewoo827@naver.com','오류가 너무 많습니다.','지금 장난하시나요? 이딴 것도 사이트라고 만드신 거면 반성하시기 바랍니다.', SYSDATE, '0', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'jewoo827@naver.com','친구 게시글이 안 보입니다.','친구로 등록된 상태인데도 홈에 친구 게시글이 뜨지 않습니다.', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'jewoo827@naver.com','인터페이스가 너무 구립니다.','좀 업데이트 바랍니다.', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'jewoo827@naver.com','시계가 안 맞습니다.','시계가 9시간 빠른 시간으로 뜨는데 왜 그럴까요?', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'jewoo827@naver.com','사진 업로드 시','사진 업로드 시 사진 크기에 제한이 있나요?', SYSDATE, '1', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'jewoo827@naver.com','닉네임에 오타가 났는데 수정 안될까요?','닉네임에 오타가 나서 수정을 하고 싶습니다.', SYSDATE, '0', null, null);
INSERT INTO INQUIRY VALUES (NUM_SEQ.NEXTVAL, 'jewoo827@naver.com','회원 탈퇴','회원 탈퇴는 어디서 진행하면 되나요?', SYSDATE, '1', null, null);

--INQUIRY (문의 답변 처리)
UPDATE INQUIRY SET INQUIRY_COMMENT = '안녕하세요. 문의주신 내용에 대하여 답변 드립니다.', INQUIRY_COMMENT_DATE = SYSDATE WHERE INQUIRY_INDEX = '1';

--NOTICE (공지)
INSERT INTO NOTICE VALUES (NUM_SEQ.NEXTVAL, '3월 업데이트 내역 공지','안녕하세요. 으밀아밀 운영자입니다. 3월에 업데이트 예정인 기능을 소개드립니다.', SYSDATE);
INSERT INTO NOTICE VALUES (NUM_SEQ.NEXTVAL, '악성 유저 기준 안내','안녕하세요. 으밀아밀 운영자입니다. 악성 유저 신고 접수 기준에 대하여 안내드립니다. 1. 게시글 혹은 댓글 도배 2. 부적절한 단어를 포함한 ID, 닉네임, 프로필, 게시글, 댓글 3. 광고성 게시글 및 댓글', SYSDATE);
INSERT INTO NOTICE VALUES (NUM_SEQ.NEXTVAL, '점검 안내','안녕하세요. 으밀아밀 운영자입니다. 4월 15일 15:00 ~ 17:00 에 잠시 점검이 있을 예정입니다. 이용에 제한이 있을 수 있는 점 참고 부탁드립니다.', SYSDATE);
INSERT INTO NOTICE VALUES (NUM_SEQ.NEXTVAL, '30일 매일 일기 도전 이벤트','안녕하세요. 으밀아밀 운영자입니다. 4월 17일부터 30일간 메일 게시글을 작성한 회원 중 추첨을 통하여 10명에게 메가커피 상품권을 드릴 예정입니다. 많은 참여 부탁드립니다.', SYSDATE);
INSERT INTO NOTICE VALUES (NUM_SEQ.NEXTVAL, '문의 답변 지연에 대하여','현재 문의가 너무 많아 답변이 지연되고 있습니다. 최대한 빠른 시일 내에 모두 답변 드릴 수 있도록 노력하겠습니다.', SYSDATE);
INSERT INTO NOTICE VALUES (NUM_SEQ.NEXTVAL, '자주오는 문의에 대하여','현재 비슷한 문의가 많이 접수되어 공지사항으로 먼저 간단하게 답변 드리려고 합니다. 프로필사진 수정 오류의 경우, 으밀아밀 서버의 문제로 내일 오전 중에 조치가 될 예정입니다.', SYSDATE);
INSERT INTO NOTICE VALUES (NUM_SEQ.NEXTVAL, '발견된 오류 조치','프로필사진 수정 오류의 조치가 완료되었습니다.', SYSDATE);

--FRIEND (친구 추가 *수락과정 생략)
INSERT INTO FRIEND VALUES (NUM_SEQ.NEXTVAL, 'jewoo827@naver.com','test1@gmail.com', SYSDATE, '1');
INSERT INTO FRIEND VALUES (NUM_SEQ.NEXTVAL, 'jewoo827@naver.com','semo@naver.com', SYSDATE, '1');
INSERT INTO FRIEND VALUES (NUM_SEQ.NEXTVAL, 'jewoo827@naver.com','nemo@daum.net', SYSDATE, '1');
INSERT INTO FRIEND VALUES (NUM_SEQ.NEXTVAL, 'jewoo827@naver.com','kbj@naver.com', SYSDATE, '1');
INSERT INTO FRIEND VALUES (NUM_SEQ.NEXTVAL, 'jewoo827@naver.com','skfktkfkd@naver.com', SYSDATE, '1');
INSERT INTO FRIEND VALUES (NUM_SEQ.NEXTVAL, 'semo@naver.com','kangsj@naver.com', SYSDATE, '1');
INSERT INTO FRIEND VALUES (NUM_SEQ.NEXTVAL, 'semo@naver.com','ccc0719@naver.com', SYSDATE, '1');
INSERT INTO FRIEND VALUES (NUM_SEQ.NEXTVAL, 'semo@naver.com','dditlove@naver.com', SYSDATE, '1');
INSERT INTO FRIEND VALUES (NUM_SEQ.NEXTVAL, 'semo@naver.com','one111@naver.com', SYSDATE, '1');
INSERT INTO FRIEND VALUES (NUM_SEQ.NEXTVAL, 'nemo@daum.net','lovelove@naver.com', SYSDATE, '1');
INSERT INTO FRIEND VALUES (NUM_SEQ.NEXTVAL, 'nemo@daum.net','ccc0719@naver.com', SYSDATE, '1');
INSERT INTO FRIEND VALUES (NUM_SEQ.NEXTVAL, 'nemo@daum.net','dditlove@naver.com', SYSDATE, '1');
INSERT INTO FRIEND VALUES (NUM_SEQ.NEXTVAL, 'nemo@daum.net','one111@naver.com', SYSDATE, '1');

commit;